$HYDE_HYPRLAND=set #! Do not remove - HyDE marker to prevent file overwrite

#* You can freely edit this file, but make sure to not remove the above line!
#* All Files Below are yours to modify!

#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/


# ------------------------------------------------------
#TODO Please remove this block if you are sure $HYPRLAND_CONFIG is set
#? This is only use for fallback
source = $HOME/.local/share/hyde/hyprland.conf # Fallback when HYPRLAND_CONFIG is not set
# -------------------------------------------------------

#? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

source = ./keybindings.conf # Keyboard shortcuts
source = ./windowrules.conf # Window rules
source = ./monitors.conf # Monitor configuration
source = ./userprefs.conf # Your hyprland configuration // Edit this file to change your Hyprland configuration

exec-once = ~/.local/lib/hyde/wallpaper.hyprpaper.sh ~/Pictures/Wallpaper/cc_warm.jpg

general {
    gaps_in = 6
    gaps_out = 12

    border_size = 2

    col.active_border = rgba(89b4faff) rgba(cba6f7ff) 45deg
    col.inactive_border = rgba(313244aa)

    layout = dwindle
}

decoration {
    rounding = 10
    active_opacity = 0.8
    inactive_opacity = 0.7

    blur {
  	enabled = no
    	size = 10
    	passes = 4
    	ignore_opacity = true
    	new_optimizations = true
        xray = false
    }

    shadow {
        enabled = no
        range = 25
        render_power = 3
        color = rgba(00000055)
    }
}

animations {
    enabled = no

    bezier = smooth, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, smooth
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

windowrule = opacity 0.85 0.75, match:class ^(kitty)$
windowrule = no_blur on, match:class ^(kitty)$
windowrule = opacity 0.85 0.75, match:class ^(code-oss)$
windowrule = no_blur on, match:class ^(code-oss)$
windowrule = opacity 0.85 0.75, match:class ^(Thunar)$
windowrule = no_blur on, match:class ^(Thunar)$
